// flow-typed signature: f3025431d51bef7c30ea94c9c9a729f5
// flow-typed version: <<STUB>>/@types/antd_v^1.0.0/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/antd'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/antd' {
  declare module.exports: any;
}
