// flow-typed signature: 3a2d033b239f0eaac06b15f4765911cb
// flow-typed version: <<STUB>>/@types/axios_v^0.14.0/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/axios'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/axios' {
  declare module.exports: any;
}
