// flow-typed signature: c26ec3d2724a3cc6321dc8d630641822
// flow-typed version: <<STUB>>/@types/chalk_v^2.2.0/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/chalk'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/chalk' {
  declare module.exports: any;
}
