// flow-typed signature: f9b7ac9da64891c3c5b1253c029d7e7e
// flow-typed version: <<STUB>>/@types/classnames_v^2.2.6/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/classnames'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/classnames' {
  declare module.exports: any;
}
