// flow-typed signature: 515884bd446e22635dfc13419e7dbdef
// flow-typed version: <<STUB>>/@types/convict_v^4.2.0/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/convict'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/convict' {
  declare module.exports: any;
}
