// flow-typed signature: 01387b9368e1cddf4de680f78c695a24
// flow-typed version: <<STUB>>/@types/date-fns_v^2.6.0/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/date-fns'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/date-fns' {
  declare module.exports: any;
}
