// flow-typed signature: 1bf14788bd3e4c6b5fdbb3ee6130eab0
// flow-typed version: <<STUB>>/@types/express-promise-router_v^2.0.0/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/express-promise-router'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/express-promise-router' {
  declare module.exports: any;
}
