// flow-typed signature: c5823d37b155f6f1469ec824e621d02c
// flow-typed version: <<STUB>>/@types/history_v^4.7.0/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/history'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/history' {
  declare module.exports: any;
}
