// flow-typed signature: fba569d50e152e4fdd69256ea5edabd6
// flow-typed version: <<STUB>>/@types/js-base64_v^2.3.1/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/js-base64'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/js-base64' {
  declare module.exports: any;
}
