// flow-typed signature: 160ab156c828963b3413a8e1b1fb8f47
// flow-typed version: <<STUB>>/@types/jwt-decode_v^2.2.1/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/jwt-decode'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/jwt-decode' {
  declare module.exports: any;
}
