// flow-typed signature: b728e06783a9b3085cb6da160bdc0683
// flow-typed version: <<STUB>>/@types/lodash.throttle_v^4.1.4/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/lodash.throttle'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/lodash.throttle' {
  declare module.exports: any;
}
