// flow-typed signature: 6497f2a9d6f3f21945d93badb63a8617
// flow-typed version: <<STUB>>/@types/lodash.debounce_v^4.0.4/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/lodash.debounce'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/lodash.debounce' {
  declare module.exports: any;
}
