// flow-typed signature: 09c5b79323eae83c56de3da62a8f1090
// flow-typed version: <<STUB>>/@types/popper.js_v^1.11.0/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/popper.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/popper.js' {
  declare module.exports: any;
}
