// flow-typed signature: 4580d45d079a87fb0c2fc94b79ae2f9a
// flow-typed version: <<STUB>>/@types/react-router_v^4.0.30/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/react-router'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/react-router' {
  declare module.exports: any;
}
