// flow-typed signature: 7ad7586589d225684e76eb74c74da7c3
// flow-typed version: <<STUB>>/@types/react-router-redux_v^5.0.15/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/react-router-redux'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/react-router-redux' {
  declare module.exports: any;
}
