// flow-typed signature: 1d0c6080b5163b16be079f6dd94da357
// flow-typed version: <<STUB>>/@types/react-motion_v^0.0.27/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/react-motion'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/react-motion' {
  declare module.exports: any;
}
