// flow-typed signature: e736ad1f86a488415cd3e078c2938193
// flow-typed version: <<STUB>>/@types/react-dom_v^16.0.7/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/react-dom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/react-dom' {
  declare module.exports: any;
}
