// flow-typed signature: 3deead4c338c5f5c2782086597a27010
// flow-typed version: <<STUB>>/@types/recompose_v^0.26.4/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/recompose'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/recompose' {
  declare module.exports: any;
}
