// flow-typed signature: b5f38c3776b92c41f88c9668dcc63e07
// flow-typed version: <<STUB>>/@types/redux-thunk_v^2.1.0/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/redux-thunk'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/redux-thunk' {
  declare module.exports: any;
}
