// flow-typed signature: f3dac176045b1ac70657984a888b4074
// flow-typed version: <<STUB>>/@types/serialize-javascript_v^1.3.2/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/serialize-javascript'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/serialize-javascript' {
  declare module.exports: any;
}
