// flow-typed signature: 974c0659f7c3eff5558ea9458ff622b5
// flow-typed version: <<STUB>>/@types/smoothscroll-polyfill_v^0.3.0/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/smoothscroll-polyfill'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/smoothscroll-polyfill' {
  declare module.exports: any;
}
