// flow-typed signature: b4cefe47ff64d59b9af2f659c133e0b5
// flow-typed version: <<STUB>>/@types/webpack_v^4.4.11/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/webpack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/webpack' {
  declare module.exports: any;
}
