// flow-typed signature: 28fcbbc1d9f18732d0f0ad21fd87cbea
// flow-typed version: <<STUB>>/antd-iconfont_v^3.0.3/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'antd-iconfont'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'antd-iconfont' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'antd-iconfont/iconfont' {
  declare module.exports: any;
}

// Filename aliases
declare module 'antd-iconfont/iconfont.js' {
  declare module.exports: $Exports<'antd-iconfont/iconfont'>;
}
