// flow-typed signature: aaac2868a63eea4e17aa41fd1b6b439a
// flow-typed version: <<STUB>>/less-vars-to-js_v^1.3.0/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'less-vars-to-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'less-vars-to-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'less-vars-to-js/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'less-vars-to-js/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'less-vars-to-js/dist/index' {
  declare module.exports: any;
}

declare module 'less-vars-to-js/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'less-vars-to-js/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'less-vars-to-js/coverage/lcov-report/prettify'>;
}
declare module 'less-vars-to-js/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'less-vars-to-js/coverage/lcov-report/sorter'>;
}
declare module 'less-vars-to-js/dist/index.js' {
  declare module.exports: $Exports<'less-vars-to-js/dist/index'>;
}
declare module 'less-vars-to-js/test/index.js' {
  declare module.exports: $Exports<'less-vars-to-js/test/index'>;
}
