// flow-typed signature: fd5276fb48fc7c6516a050f911154d84
// flow-typed version: <<STUB>>/modernizr-webpack-plugin_v^1.0.7/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'modernizr-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'modernizr-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'modernizr-webpack-plugin/index' {
  declare module.exports: $Exports<'modernizr-webpack-plugin'>;
}
declare module 'modernizr-webpack-plugin/index.js' {
  declare module.exports: $Exports<'modernizr-webpack-plugin'>;
}
