// flow-typed signature: c0a0e6821d0410df26caae65da92a26f
// flow-typed version: <<STUB>>/webpack-require-from_v^1.3.1/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-require-from'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-require-from' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-require-from/example/a' {
  declare module.exports: any;
}

declare module 'webpack-require-from/example/b' {
  declare module.exports: any;
}

declare module 'webpack-require-from/example/c' {
  declare module.exports: any;
}

declare module 'webpack-require-from/example/d' {
  declare module.exports: any;
}

declare module 'webpack-require-from/example/index' {
  declare module.exports: any;
}

declare module 'webpack-require-from/example/webpack.config' {
  declare module.exports: any;
}

declare module 'webpack-require-from/src/codeBuilders' {
  declare module.exports: any;
}

declare module 'webpack-require-from/src/constants' {
  declare module.exports: any;
}

declare module 'webpack-require-from/src/helpers' {
  declare module.exports: any;
}

declare module 'webpack-require-from/src/plugin' {
  declare module.exports: any;
}

declare module 'webpack-require-from/test/common/index' {
  declare module.exports: any;
}

declare module 'webpack-require-from/test/common/moduleB' {
  declare module.exports: any;
}

declare module 'webpack-require-from/test/common/moduleC' {
  declare module.exports: any;
}

declare module 'webpack-require-from/test/common/tests' {
  declare module.exports: any;
}

declare module 'webpack-require-from/test/common/webpack.config.shared' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-require-from/example/a.js' {
  declare module.exports: $Exports<'webpack-require-from/example/a'>;
}
declare module 'webpack-require-from/example/b.js' {
  declare module.exports: $Exports<'webpack-require-from/example/b'>;
}
declare module 'webpack-require-from/example/c.js' {
  declare module.exports: $Exports<'webpack-require-from/example/c'>;
}
declare module 'webpack-require-from/example/d.js' {
  declare module.exports: $Exports<'webpack-require-from/example/d'>;
}
declare module 'webpack-require-from/example/index.js' {
  declare module.exports: $Exports<'webpack-require-from/example/index'>;
}
declare module 'webpack-require-from/example/webpack.config.js' {
  declare module.exports: $Exports<'webpack-require-from/example/webpack.config'>;
}
declare module 'webpack-require-from/index' {
  declare module.exports: $Exports<'webpack-require-from'>;
}
declare module 'webpack-require-from/index.js' {
  declare module.exports: $Exports<'webpack-require-from'>;
}
declare module 'webpack-require-from/src/codeBuilders.js' {
  declare module.exports: $Exports<'webpack-require-from/src/codeBuilders'>;
}
declare module 'webpack-require-from/src/constants.js' {
  declare module.exports: $Exports<'webpack-require-from/src/constants'>;
}
declare module 'webpack-require-from/src/helpers.js' {
  declare module.exports: $Exports<'webpack-require-from/src/helpers'>;
}
declare module 'webpack-require-from/src/plugin.js' {
  declare module.exports: $Exports<'webpack-require-from/src/plugin'>;
}
declare module 'webpack-require-from/test/common/index.js' {
  declare module.exports: $Exports<'webpack-require-from/test/common/index'>;
}
declare module 'webpack-require-from/test/common/moduleB.js' {
  declare module.exports: $Exports<'webpack-require-from/test/common/moduleB'>;
}
declare module 'webpack-require-from/test/common/moduleC.js' {
  declare module.exports: $Exports<'webpack-require-from/test/common/moduleC'>;
}
declare module 'webpack-require-from/test/common/tests.js' {
  declare module.exports: $Exports<'webpack-require-from/test/common/tests'>;
}
declare module 'webpack-require-from/test/common/webpack.config.shared.js' {
  declare module.exports: $Exports<'webpack-require-from/test/common/webpack.config.shared'>;
}
